### ISSUE TITLE
Consider CSS Modules and flexbox component

### ISSUE THREAD

**Issue by daiky00** [zebapy/create-react-app-parse-redux#11]
Have you thought about implementing Modular CSS on this example app? also I will recommend to include http://roylee0704.github.io/react-flexbox-grid/ :)

**Comment by zebapy** [comment]
@daiky00 I have not considered adding anything else at the moment. I want to use create-react-app as much as possible out of the box for the client side, and currently it doesn't support CSS modules or similar. I'm sure it could be added in another manner but I'd wait until CRA has support for it (though it seems unlikely for awhile https://github.com/facebookincubator/create-react-app/issues/78#issuecomment-245727905)

As for a flexbox component, I'd rather leave it up to the developer for what they want to use for layout, etc (though flexbox is becoming more common). 

This is really mean to be the main ground for using ParseServer and CRA. Nothing more really. I don't have any goals for the project at the moment, I haven't had a chance to keep up with updating dependencies greenkeeper submits. If anything, I think some tests and CI would be good for the repo. 

Really appreciate the feedback, though! I don't maintain many public repos that get any sort of attention.
