### ISSUE TITLE
won't start unless index.html placed in public dir

### ISSUE THREAD

**Issue by owldesign** [zebapy/create-react-app-parse-redux#34]
I had to create `/public/` and move the`index.html` for `npm start` to run..kept getting this error 
```
    Could not find a required file.
        Name: index.html
        Searched in: /Users/****/Sites/create-react-app-parse-redux/public

```

**Comment by pcegarra** [comment]
Thanks, I had the same problem

**Comment by day** [comment]
Same. I actually changed the `package.json` like so:
```"build": "react-scripts build && cp build/index.html public/index.html"```
Seems to work fine...but not sure why it doesn't work out of the box.

**Comment by mwayne16** [comment]
You can actually change where react looks for the index.html file by going to ./node_modules/react-scripts/config/paths.js. Look for "appDirectory". by default it will point to the project directory but you can change this to whatever you'd like with path.join(). 

const appDirectory = fs.realpathSync(path.join(process.cwd(), 'directory location'));

**Comment by capitalF03** [comment]
i am able to see many index.js files
