### ISSUE TITLE
refreshing url is removing the state ?

### ISSUE THREAD

**Issue by khawtf** [zebapy/create-react-app-parse-redux#39]
Hi awsome job on this starter kit. 

Maybe I have found a small issue...after logging in and refreshing the page the user is nog logged in anymore

**Comment by zebapy** [comment]
@khawtf correct, that would be some sort of "remember me" functionality which isn't part of this starter. You can easily create it by wrapping the app with another component that reads the token from localStorage on `componentDidMount` and dispatches some sort of `authWithToken` action to send it to the API and retrieve user info. It's just not part of this boilerplate.
